# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\KTK\Desktop\BDProject\SCADA\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginScreen(object):
    def setupUi(self, LoginScreen):
        LoginScreen.setObjectName("LoginScreen")
        LoginScreen.resize(600, 600)
        self.widget = QtWidgets.QWidget(LoginScreen)
        self.widget.setGeometry(QtCore.QRect(0, 0, 601, 601))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.96, y1:0.892364, x2:0.926318, y2:0.738, stop:0 rgba(173, 0, 0, 255), stop:0.977273 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 321, 121))
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\KTK\\Desktop\\BDProject\\SCADA\\img/YASARTLogo.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(400, 60, 161, 121))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\KTK\\Desktop\\BDProject\\SCADA\\img/PEAELogo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.UserName = QtWidgets.QLineEdit(self.widget)
        self.UserName.setGeometry(QtCore.QRect(110, 250, 181, 31))
        self.UserName.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.UserName.setClearButtonEnabled(True)
        self.UserName.setObjectName("UserName")
        self.Password = QtWidgets.QLineEdit(self.widget)
        self.Password.setGeometry(QtCore.QRect(110, 310, 181, 31))
        self.Password.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setClearButtonEnabled(True)
        self.Password.setObjectName("Password")
        self.LoginButton = QtWidgets.QPushButton(self.widget)
        self.LoginButton.setGeometry(QtCore.QRect(240, 420, 151, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LoginButton.setFont(font)
        self.LoginButton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: qlineargradient(spread:pad, x1:0.0454091, y1:0.068, x2:0.306, y2:0.569, stop:0 rgba(129, 0, 0, 255), stop:0.977273 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.LoginButton.setObjectName("LoginButton")
        self.LoggedInLabel = QtWidgets.QLabel(self.widget)
        self.LoggedInLabel.setGeometry(QtCore.QRect(110, 350, 301, 31))
        self.LoggedInLabel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(0, 0, 0, 0);")
        self.LoggedInLabel.setText("")
        self.LoggedInLabel.setObjectName("LoggedInLabel")

        self.retranslateUi(LoginScreen)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)

    def retranslateUi(self, LoginScreen):
        _translate = QtCore.QCoreApplication.translate
        LoginScreen.setWindowTitle(_translate("LoginScreen", "Login"))
        self.UserName.setPlaceholderText(_translate("LoginScreen", "User Name"))
        self.Password.setPlaceholderText(_translate("LoginScreen", "Password"))
        self.LoginButton.setText(_translate("LoginScreen", "Login"))
import PEAELogo_rc
import YASARTLogo_rc
