# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\KTK\Desktop\BDProject\SCADA\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cirProgBar = QtWidgets.QFrame(self.centralwidget)
        self.cirProgBar.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.cirProgBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cirProgBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cirProgBar.setObjectName("cirProgBar")
        self.cirProg = QtWidgets.QFrame(self.cirProgBar)
        self.cirProg.setGeometry(QtCore.QRect(10, 10, 200, 200))
        self.cirProg.setStyleSheet("QFrame{\n"
"border-radius: 100px;\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.819892 rgba(0, 0, 8, 0), stop:0.820892 rgba(129, 0, 0, 255));\n"
"}")
        self.cirProg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cirProg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cirProg.setObjectName("cirProg")
        self.frame = QtWidgets.QFrame(self.cirProgBar)
        self.frame.setGeometry(QtCore.QRect(10, 10, 200, 200))
        self.frame.setStyleSheet("QFrame{\n"
"border-radius: 100px;\n"
"background-color: rgba(77, 77, 127, 150);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.cirProgBar)
        self.frame_2.setGeometry(QtCore.QRect(20, 20, 180, 180))
        self.frame_2.setStyleSheet("QFrame{\n"
"border-radius: 90;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 161, 134))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.progValue2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.progValue2.setFont(font)
        self.progValue2.setStyleSheet("color: rgb(129, 0, 0);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.progValue2.setAlignment(QtCore.Qt.AlignCenter)
        self.progValue2.setObjectName("progValue2")
        self.gridLayout.addWidget(self.progValue2, 3, 0, 1, 1)
        self.name = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setStyleSheet("color: rgb(129, 0, 0);\n"
"background-color: rgb(85, 170, 255);\n"
"border-radius: 10px")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 0, 1, 1)
        self.progValue1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.progValue1.setFont(font)
        self.progValue1.setStyleSheet("color: rgb(129, 0, 0);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.progValue1.setAlignment(QtCore.Qt.AlignCenter)
        self.progValue1.setObjectName("progValue1")
        self.gridLayout.addWidget(self.progValue1, 0, 0, 1, 1)
        self.frame.raise_()
        self.cirProg.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 21))
        self.menubar.setObjectName("menubar")
        self.AboutTab = QtWidgets.QMenu(self.menubar)
        self.AboutTab.setObjectName("AboutTab")
        MainWindow.setMenuBar(self.menubar)
        self.actionAboutYASART = QtWidgets.QAction(MainWindow)
        self.actionAboutYASART.setObjectName("actionAboutYASART")
        self.actionAboutPEAE = QtWidgets.QAction(MainWindow)
        self.actionAboutPEAE.setObjectName("actionAboutPEAE")
        self.actionAbout_Tiqur_wha = QtWidgets.QAction(MainWindow)
        self.actionAbout_Tiqur_wha.setObjectName("actionAbout_Tiqur_wha")
        self.AboutTab.addAction(self.actionAboutYASART)
        self.AboutTab.addAction(self.actionAboutPEAE)
        self.AboutTab.addAction(self.actionAbout_Tiqur_wha)
        self.menubar.addAction(self.AboutTab.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.progValue2.setText(_translate("MainWindow", "<p><span style=\" font-size:24pt; color:#430000;\">0</span><span style=\" font-size:20pt; color:#430000;\">Kpa</span></p>"))
        self.name.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">SPump 1</span></p></body></html>"))
        self.progValue1.setText(_translate("MainWindow", "<p><span style=\" color:#430000;\">0</span><span style=\" color:#430000; vertical-align:super;\">L/s</span></p>"))
        self.AboutTab.setTitle(_translate("MainWindow", "About"))
        self.actionAboutYASART.setText(_translate("MainWindow", "About YASART"))
        self.actionAboutPEAE.setText(_translate("MainWindow", "About PEAI"))
        self.actionAbout_Tiqur_wha.setText(_translate("MainWindow", "About Tiqur-wha"))
